CREATE DATABASE LIGA_ARENA;

USE LIGA_ARENA;

CREATE TABLE TBL_CATEGORIAPRODUTOS (
  CAP_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  CAP_NOME VARCHAR(20) NOT NULL,
  PRIMARY KEY(CAP_CODIGO)
);

CREATE TABLE TBL_ESTADOS (
  EST_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  EST_DESCRICAO VARCHAR(20) NOT NULL,
  EST_UF CHAR(2) NOT NULL,
  PRIMARY KEY(EST_CODIGO)
);

CREATE TABLE TBL_CATEGORIADESPESAS (
  CAD_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  CAD_DESCRICAO VARCHAR(20) NOT NULL,
  PRIMARY KEY(CAD_CODIGO)
);

CREATE TABLE TBL_CARDAPIOS (
  CAR_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  CAR_VALOR FLOAT NOT NULL,
  CAR_ATIVO TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY(CAR_CODIGO)
);

CREATE TABLE TBL_PRODUTOS (
  PRO_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  TBL_CATEGORIAPRODUTOS_CAP_CODIGO INTEGER NOT NULL,
  PRO_DESCRICAO VARCHAR(50) NOT NULL,
  PRO_VALORCUSTO FLOAT NOT NULL,
  PRO_DATAVALIDADE DATE NULL,
  PRO_UNMEDIDA VARCHAR(20) NOT NULL,
  PRO_QTDATUAL INTEGER NOT NULL,
  PRO_QTDMINIMA INTEGER NOT NULL,
  PRO_ATIVO TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY(PRO_CODIGO),
  INDEX TBL_PRODUTO_FKIndex1(TBL_CATEGORIAPRODUTOS_CAP_CODIGO),
  FOREIGN KEY(TBL_CATEGORIAPRODUTOS_CAP_CODIGO)
    REFERENCES TBL_CATEGORIAPRODUTOS(CAP_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_CIDADES (
  CID_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  TBL_ESTADOS_EST_CODIGO INTEGER NOT NULL,
  CID_DESCRICAO VARCHAR(50) NOT NULL,
  PRIMARY KEY(CID_CODIGO),
  INDEX TBL_CIDADES_FKIndex1(TBL_ESTADOS_EST_CODIGO),
  FOREIGN KEY(TBL_ESTADOS_EST_CODIGO)
    REFERENCES TBL_ESTADOS(EST_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_ENDERECOS (
  END_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  TBL_CIDADES_CID_CODIGO INTEGER NOT NULL,
  END_LOGRADOURO VARCHAR(50) NOT NULL,
  END_NUMERO VARCHAR(5) NOT NULL,
  END_COMPLEMENTO VARCHAR(20) NULL,
  END_BAIRRO VARCHAR(30) NOT NULL,
  END_CEP VARCHAR(9) NOT NULL,
  PRIMARY KEY(END_CODIGO),
  INDEX TBL_ENDERECO_FKIndex1(TBL_CIDADES_CID_CODIGO),
  FOREIGN KEY(TBL_CIDADES_CID_CODIGO)
    REFERENCES TBL_CIDADES(CID_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_CARDAPIOS_has_TBL_PRODUTOS (
  TBL_CARDAPIOS_CAR_CODIGO INTEGER NOT NULL,
  TBL_PRODUTOS_PRO_CODIGO INTEGER NOT NULL,
  PRIMARY KEY(TBL_CARDAPIOS_CAR_CODIGO, TBL_PRODUTOS_PRO_CODIGO),
  INDEX TBL_CARDAPIOS_has_TBL_PRODUTOS_FKIndex1(TBL_CARDAPIOS_CAR_CODIGO),
  INDEX TBL_CARDAPIOS_has_TBL_PRODUTOS_FKIndex2(TBL_PRODUTOS_PRO_CODIGO),
  FOREIGN KEY(TBL_CARDAPIOS_CAR_CODIGO)
    REFERENCES TBL_CARDAPIOS(CAR_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(TBL_PRODUTOS_PRO_CODIGO)
    REFERENCES TBL_PRODUTOS(PRO_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_PESSOAS (
  PES_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  PES_TIPO VARCHAR(20) NOT NULL,
  PES_NOME VARCHAR(50) NOT NULL,
  PES_CPF VARCHAR(14) NULL,
  PES_CNPJ VARCHAR(18) NULL,
  TBL_ENDERECOS_END_CODIGO INTEGER NOT NULL,
  PES_TELEFONE VARCHAR(13) NULL,
  PES_DATACADASTRO DATE NULL,
  PES_DATANASCIMENTO DATE NULL,
  PES_NUMEROREGISTRO INTEGER NULL,
  PES_CARGO VARCHAR(20) NULL,
  PES_SALARIO FLOAT NULL,
  PES_DATAADMISSAO DATE NULL,
  PES_EMAIL VARCHAR(30) NOT NULL,
  PES_SENHA VARCHAR(20) NOT NULL,
  PES_SEXO VARCHAR(10) NOT NULL,
  PES_ATIVO TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY(PES_CODIGO),
  INDEX TBL_PESSOA_FKIndex1(TBL_ENDERECOS_END_CODIGO),
  FOREIGN KEY(TBL_ENDERECOS_END_CODIGO)
    REFERENCES TBL_ENDERECOS(END_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_DESPESAS (
  DES_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  TBL_PESSOAS_PES_CODIGO INTEGER NOT NULL,
  TBL_CATEGORIADESPESAS_CAD_CODIGO INTEGER NOT NULL,
  DES_DESCRICAO VARCHAR(50) NOT NULL,
  DES_CUSTO FLOAT NOT NULL,
  DES_DATA DATE NOT NULL,
  PRIMARY KEY(DES_CODIGO),
  INDEX TBL_DESPESA_FKIndex1(TBL_CATEGORIADESPESAS_CAD_CODIGO),
  INDEX TBL_DESPESA_FKIndex2(TBL_PESSOAS_PES_CODIGO),
  FOREIGN KEY(TBL_CATEGORIADESPESAS_CAD_CODIGO)
    REFERENCES TBL_CATEGORIADESPESAS(CAD_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(TBL_PESSOAS_PES_CODIGO)
    REFERENCES TBL_PESSOAS(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_FEEDBACKS (
  FED_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  TBL_PESSOAS_PES_CODIGO INTEGER NOT NULL,
  FED_NOTA TINYINT(2) NOT NULL,
  FED_DESCRICAO TEXT(500) NULL,
  PRIMARY KEY(FED_CODIGO),
  INDEX TBL_FEEDBACK_FKIndex1(TBL_PESSOAS_PES_CODIGO),
  FOREIGN KEY(TBL_PESSOAS_PES_CODIGO)
    REFERENCES TBL_PESSOAS(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_PEDIDOS (
  PED_CODIGO INTEGER NOT NULL AUTO_INCREMENT,
  TBL_PESSOAS_PES_CODIGO INTEGER NOT NULL,
  PED_NUMEROMESA TINYINT(2) NOT NULL,
  PED_QTDITEM INTEGER NOT NULL,
  PED_DATAHORA DATETIME NOT NULL,
  PED_VALORTOTAL FLOAT NULL,
  PED_PAGO TINYINT(1) UNSIGNED NULL,
  PED_STATUS TINYINT(1) UNSIGNED NULL,
  PRIMARY KEY(PED_CODIGO),
  INDEX TBL_PEDIDO_FKIndex1(TBL_PESSOAS_PES_CODIGO),
  FOREIGN KEY(TBL_PESSOAS_PES_CODIGO)
    REFERENCES TBL_PESSOAS(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE TBL_PEDIDOS_CARDAPIOS (
  TBL_PEDIDOS_PED_CODIGO INTEGER NOT NULL,
  TBL_CARDAPIOS_CAR_CODIGO INTEGER NOT NULL,
  CAR_VALOR FLOAT NOT NULL,
  PED_QUANTIDADE INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(TBL_PEDIDOS_PED_CODIGO, TBL_CARDAPIOS_CAR_CODIGO),
  INDEX TBL_PEDIDO_has_TBL_CARDAPIO_FKIndex1(TBL_PEDIDOS_PED_CODIGO),
  INDEX TBL_PEDIDO_has_TBL_CARDAPIO_FKIndex2(TBL_CARDAPIOS_CAR_CODIGO),
  FOREIGN KEY(TBL_PEDIDOS_PED_CODIGO)
    REFERENCES TBL_PEDIDOS(PED_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(TBL_CARDAPIOS_CAR_CODIGO)
    REFERENCES TBL_CARDAPIOS(CAR_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);